apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fdsagassa
    backstage.io/kubernetes-id: fdsagassa
  name: fdsagassa
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdsagassa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fdsagassa
        backstage.io/kubernetes-id: fdsagassa
    spec:
      containers:
      - image: '{{ .Values.config.image.name }}':'{{ .Values.config.image.tag }}'
        imagePullPolicy: IfNotPresent
        name: fdsagassa
        resources: {}
        ports:
          - containerPort: 8080 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 5
status: {}
