apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fdsagassa
    backstage.io/kubernetes-id: fdsagassa
  name: fdsagassa
  namespace: '{{ .Values.config.namespace }}'
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fdsagassa
